baseURL: https://cultureofcode.com/
languageCode: en-us
title: "Culture of Code"
theme: coc
paginate: 7
params:
  authorDisplayName: kenneth
  authorUrl: https://kennethbowen.com
  authorEmail: kenneth@kennethbowen.com
