baseURL: https://cultureofcode.com/
languageCode: en
title: "Culture of Code"
theme: coc
paginate: 7
ignoreErrors:
  - "error-remote-getjson"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokailight
    tabWidth: 2

params:
  authorDisplayName: kenneth
  authorUrl: https://kennethbowen.com
  authorEmail: kenneth@kennethbowen.com
  description: "Digital fuel for an empty tank world"
